### PR TITLE
Added better documentation on getting the Rails project set up

### PR DESCRIPTION
**Pull request by JohnSmall**
I've added better documentation on how to set up the Rails project, including running the tests and seeding the database with sample data. 

If you look in html/index.html you'll see it.

Plus some updates to the code and api documentation.

### CODE REVIEW

**Comment by elischutze** [comment]
looks good, is this for a particular issue?

**Comment by JohnSmall** [comment]
Fixes in the latest commit
1) We can now use the api to add links between meetings, hospitality & etc, to people, government offices and organisations. I've extended the documentation with specific examples of calls to the api to do it.

2) We can now search people. government offices and organisations by name. This is essential when adding new entries so we check if they exist first before we add them.

As there's no conflict with master, shall I just merge?

**Comment by eddiejaoude** [comment]
@JohnSmall just a suggestion... continuing to add to this **PR** will make it more difficult to review & therefore get merged in. I suggest keeping **PR**s small in the future & each **PR** only addressing a single feature - 92 files changes in a PR for _documentation_ seems excessive

**Comment by eddiejaoude** [comment]
> As there's no conflict with master, shall I just merge?

I dont want to deflate your hard work, but that is not the point of a [Pull Request](https://help.github.com/articles/about-pull-requests/)

**Comment by jo-osborne** [comment]
@eddiejaoude perhaps you could clarify what more should be done before @JohnSmall is able to merge? I don't feel that I particularly understand the process at the moment and it would be helpful for me to have this PR merged in.

**Comment by eddiejaoude** [comment]
Fair point @jo-osborne , the sooner PRs are merged the better - smaller PRs only solving a single issue are always merged much quicker than massive ones. I am not trying to dictate the process, but just going by general open source project practices. I suggest that the main contributors on the project review & then once happy merge, but should not be merged by the person who created the PR.

**Pull request merged**
