### PR TITLE
Create mono repo

### PR DESCRIPTION
**Pull request by jo-osborne**
I have removed the files from the original hack day because I wasn't too sure what to do with them. They are obviously still in the git history so if they are needed it would be great for someone to add them to the repo :)

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Is the `resources` directory the files from the repo `MinistersUnderTheInfluence-Data`? https://github.com/HackBrexit/MinistersUnderTheInfluence-Data

**Comment by eddiejaoude** [comment]
Looks good 👍

**Comment by jo-osborne** [comment]
The `resources` contains a subset of the more homogeneous files which I copied out of `MinistersUnderTheInfluence-Data` for ease of writing my script.

**Comment by eddiejaoude** [comment]
Might be worth having a `hackathon` folder? Then folders for each hackathon, to save people going through the _long_ history

**Comment by jo-osborne** [comment]
Good idea!

**Comment by eddiejaoude** [comment]
Looks great 👍 

@charlottebrf @elischutze please review

**Review by eddiejaoude — APPROVED** [review]
Looks good to me 👍

**Comment by charlottebrf** [comment]
Hey @jo-osborne @eddiejaoude @elischutze just merged the commit is this what you wanted me to do? Hope I haven't treaded on toes!

**Comment by eddiejaoude** [comment]
@charlottebrf 👍

**Pull request merged**
